"""add role to customer table

Revision ID: 50c5877a72a5
Revises: 2f6a7c1b9d11
Create Date: 2026-05-10 00:26:48.157776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c5877a72a5'
down_revision: Union[str, Sequence[str], None] = '2f6a7c1b9d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "customers",
        sa.Column(
            "role",
            sa.Enum("customer", "seller", "cooperative", name="customerrole"),
            nullable=False,
            server_default="customer",
        ),
    )
    op.execute("UPDATE customers SET role = 'customer' WHERE role IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'role')
    # ### end Alembic commands ###
